AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/OptionalBooleanParameter:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16