name: CI

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  cc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout master
      run: git checkout master
    - name: Run the tests with coverage using lcov
      working-directory: ./bin/app
      run: |
        npm install
        npm run test:coverage
    - name: Generate formatted coverage for codeclimate
      working-directory: ./bin/app
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x cc-test-reporter
        ./cc-test-reporter format-coverage -t lcov
    - name: Upload coverage report to codeclimate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      working-directory: ./bin/app
      run: |
        ./cc-test-reporter upload-coverage